In [2]:
#!pip install imutils
from imutils import paths 

train_image_files = list(paths.list_images('train'))
test_image_files = list(paths.list_images('test'))
val_image_files = list(paths.list_images('val'))

In [3]:
from tensorflow import keras 
import tensorflow as tf 

# Image preprocessing utils
@tf.function
def parse_images(image_path): 
    """
        this function, will read the image from the directory, and resize it to the 224 image shape, which is predefined 
        image shape of Resnet pretrained model.
        Params:
            image_path(type: str): image filepath in the directory.
        Return(type: tf.Image)
            returns the preprocessed image.
    """
    image_string = tf.io.read_file(image_path)
    image = tf.image.decode_jpeg(image_string, channels=3)
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.image.resize(image, size=[224, 224])

    return image

def create_tensorflow_dataset(data, batch_size):
    """
        this function, will create the tensorflow dataset from the images.
        Params:
            data(type: List): list of data, in our case list contains the file path.
            batch_size(type: Int): batch size for the generator.
        Return(type: tf.data.Dataset)
            returns tensorflow dataset object.
    """
    tensorflow_data = tf.data.Dataset.from_tensor_slices(train_image_files)
    tensorflow_data = (
    tensorflow_data
        .map(parse_images, num_parallel_calls=tf.data.experimental.AUTOTUNE)
        .shuffle(1024)
        .batch(batch_size, drop_remainder=True)
        .prefetch(tf.data.experimental.AUTOTUNE)
    )
    return tensorflow_data        

In [4]:
train_ds = create_tensorflow_dataset(train_image_files, 32)
test_ds = create_tensorflow_dataset(test_image_files, 32)
val_ds = create_tensorflow_dataset(val_image_files, 32)

In [5]:
import numpy as np
import cv2

class GaussianBlur(object):
    # Implements Gaussian blur as described in the SimCLR paper
    def __init__(self, kernel_size, min=0.1, max=2.0):
        self.min = min
        self.max = max
        # kernel size is set to be 10% of the image height/width
        self.kernel_size = kernel_size

    def __call__(self, sample):
        sample = np.array(sample)

        # blur the image with a 50% chance
        prob = np.random.random_sample()

        if prob < 0.5:
            sigma = (self.max - self.min) * np.random.random_sample() + self.min
            sample = cv2.GaussianBlur(sample, (self.kernel_size, self.kernel_size), sigma)

        return sample
    
gaussiam_blur = GaussianBlur(3) 
# color jitter and grayscale 
def random_color_distortion(image):
    # Random color jittering (strength 0.5)
    color_jitter = tf.random.uniform(shape=[])
    if color_jitter < 0.8:
        image = tf.image.random_brightness(image, max_delta=0.4)
        image = tf.image.random_contrast(image, lower=0.6, upper=1.4)
        image = tf.image.random_saturation(image, lower=0.6, upper=1.4)
        image = tf.image.random_hue(image, max_delta=0.1)
        image = tf.clip_by_value(image, 0, 1)

    # Color dropping
    color_drop = tf.random.uniform(shape=[])
    if color_drop < 0.2:
        image = tf.image.rgb_to_grayscale(image)
      #  image = tf.tile(image, [1, 1, 3])

    return image

def simclr_dataaugumentation_pipeline(images):
    images = tf.image.random_crop(value=images, size=(32, 100, 100, 3))
    images = tf.image.random_flip_left_right(images, seed=None)
    images = tf.image.resize(images, [224, 224])
#    images = random_color_distortion(images)
  #  images = apply_blur(images)
 #       
    return images

In [6]:
from tensorflow.keras.layers import Layer
from tensorflow.keras.layers import Dense, Input, Lambda, Input, Conv2D, MaxPooling2D, Activation, GlobalAveragePooling2D

class ProjectionHeadLayer(Layer): 
    def __init__(self, hidden_neurons=128, activation_func=None):
        super(ProjectionHeadLayer, self).__init__()
        self.hidden_neurons = hidden_neurons
        self.activation_func = activation_func
        self.dense_layer = Dense(self.hidden_neurons)
        self.act_func = Activation(self.activation_func)
        
    def call(self, tensor): 
        x = self.dense_layer(tensor)
        x = self.act_func(x)
        
        return x

In [7]:
class ProjectionHead(keras.models.Model): 
    def __init__(self):
        super(ProjectionHead, self).__init__()        
        self.projection_layer_1 = ProjectionHeadLayer(256, activation_func="relu")
        self.projection_layer_2 = ProjectionHeadLayer(128, activation_func="relu")
        self.projection_layer_3 = ProjectionHeadLayer(50, activation_func=None)
        
    def call(self, tensor): 
        x = self.projection_layer_1(tensor)
        x = self.projection_layer_2(x)
        x = self.projection_layer_3(x)
        
        return x    
    
def base_encoder(input_dims, include_top, weights): 
    base_model = tf.keras.applications.ResNet50(include_top=include_top,
                                        weights=weights, input_shape=input_dims)
    base_model.trainable = True
    inputs = Input(input_dims)
    h = base_model(inputs, training=True)
    return keras.models.Model(inputs, h)
        

In [8]:
class BaseEncoder(keras.models.Model):
    def __init__(self, input_dims, include_top, weights): 
        super(BaseEncoder, self).__init__()
        self.input_dims = input_dims
        self._include_top = include_top
        self._weights = weights
        
        self.base_encoder = base_encoder(self.input_dims , self._include_top, self._weights)
        self.projectionhead_model = ProjectionHead()
        self.global_avgpooling = GlobalAveragePooling2D()
        
    def call(self, tensor): 
        x = self.base_encoder(tensor, training=True)
        x = self.global_avgpooling(x)
        x = self.projectionhead_model(x)
        
        return x 

In [9]:
import tensorflow as tf

cosine_sim_1d = tf.keras.losses.CosineSimilarity(axis=1, reduction=tf.keras.losses.Reduction.NONE)
cosine_sim_2d = tf.keras.losses.CosineSimilarity(axis=2, reduction=tf.keras.losses.Reduction.NONE)


def _cosine_simililarity_dim1(x, y):
    v = cosine_sim_1d(x, y)
    return v


def _cosine_simililarity_dim2(x, y):
    # x shape: (N, 1, C)
    # y shape: (1, 2N, C)
    # v shape: (N, 2N)
    v = cosine_sim_2d(tf.expand_dims(x, 1), tf.expand_dims(y, 0))
    return v


def _dot_simililarity_dim1(x, y):
    # x shape: (N, 1, C)
    # y shape: (N, C, 1)
    # v shape: (N, 1, 1)
    v = tf.matmul(tf.expand_dims(x, 1), tf.expand_dims(y, 2))
    return v


def _dot_simililarity_dim2(x, y):
    v = tf.tensordot(tf.expand_dims(x, 1), tf.expand_dims(tf.transpose(y), 0), axes=2)
    # x shape: (N, 1, C)
    # y shape: (1, C, 2N)
    # v shape: (N, 2N)
    return v

def get_delayed_lr(initial_lr, decay_steps): 
    decay_steps = 1000
    lr_decayed_fn = tf.keras.experimental.CosineDecay(initial_learning_rate=initial_lr,
                                                                  decay_steps=decay_steps)
    
    return lr_decayed_fn


def get_negative_mask(batch_size):
    # return a mask that removes the similarity score of equal/similar images.
    # this function ensures that only distinct pair of images get their similarity scores
    # passed as negative examples
    negative_mask = np.ones((batch_size, 2 * batch_size), dtype=bool)
    for i in range(batch_size):
        negative_mask[i, i] = 0
        negative_mask[i, i + batch_size] = 0
    return tf.constant(negative_mask)

In [10]:
def ntxloss(zis, zjs, negatives, batch_size, 
                    criterion, negative_mask, temperature, l_pos): 
    loss = 0
    for positives in [zis, zjs]:
        l_neg = _cosine_simililarity_dim2(positives, negatives)

        labels = tf.zeros(batch_size, dtype=tf.int32)

        l_neg = tf.boolean_mask(l_neg, negative_mask)
        l_neg = tf.reshape(l_neg, (batch_size, -1))
        l_neg /= temperature
        
        logits = tf.concat([l_pos, l_neg], axis=1)         
        loss += criterion(y_pred=logits, y_true=labels)        

    loss = loss / (2 * batch_size)
    return loss

In [11]:
def train_step(ti, tj, model, optimizer, criterion, 
                                batch_size, temperature, negative_mask): 
    with tf.GradientTape() as tape: 
        zis = model(ti)
        zjs = model(tj)
        
        zis = tf.math.l2_normalize(zis, axis=1)
        zjs = tf.math.l2_normalize(zjs, axis=1)

        l_pos = _dot_simililarity_dim1(zis, zjs)
        l_pos = tf.reshape(l_pos, (batch_size, 1))
        l_pos /= temperature

        negatives = tf.concat([zis, zjs], axis=0)
        loss = ntxloss(zis, zjs, negatives, batch_size, 
                               criterion, negative_mask, temperature, l_pos)
    
    params = model.trainable_weights
    grads = tape.gradient(loss, params)
    optimizer.apply_gradients(zip(grads, params))
    
    return loss 

In [13]:
from tqdm import tqdm

def train(model, train_ds, optimizer, criterion, temperature, 
                                  epochs, batch_size, negative_mask): 
    epochs_loss = []
    for epoch in tqdm(range(epochs)):
        epoch_loss = 0
        total_iteration = 0
        for training_data_batch in train_ds: 
            tis = simclr_dataaugumentation_pipeline(training_data_batch)
            tjs = simclr_dataaugumentation_pipeline(training_data_batch)
                        
            loss = train_step(tis, tjs, model, optimizer, criterion, 
                                      batch_size, temperature, negative_mask)
            
            epoch_loss += loss 
            total_iteration += 1 
        
        mean_epoch_loss = epoch_loss / total_iteration
        epochs_loss.append(mean_epoch_loss)
        
        print(f'Epoch; {epoch} loss: {mean_epoch_loss}')
    
    return epochs_loss, model

In [17]:
base_encoder_model = BaseEncoder((224, 224, 3), False, None)
criterion = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, 
                                                          reduction=tf.keras.losses.Reduction.SUM)

optimizer = tf.keras.optimizers.SGD(get_delayed_lr(0.1, 1000))
negative_mask = get_negative_mask(32)

train(base_encoder_model, train_ds, optimizer, criterion, 0.1, 150, 32, negative_mask)

  1%|          | 1/150 [00:59<2:26:55, 59.16s/it]

Epoch; 0 loss: 1.7672856245098956e-07


  1%|▏         | 2/150 [01:52<2:17:27, 55.72s/it]

Epoch; 1 loss: 1.6903503308185464e-07


  2%|▏         | 3/150 [02:45<2:13:19, 54.42s/it]

Epoch; 2 loss: 1.7255786133318907e-07


  3%|▎         | 4/150 [03:38<2:11:00, 53.84s/it]

Epoch; 3 loss: 1.7188973799875384e-07


  3%|▎         | 5/150 [04:31<2:09:18, 53.50s/it]

Epoch; 4 loss: 1.7557452736127743e-07


  4%|▍         | 6/150 [05:24<2:07:50, 53.27s/it]

Epoch; 5 loss: 1.6927798185406573e-07


  5%|▍         | 7/150 [06:16<2:06:38, 53.13s/it]

Epoch; 6 loss: 1.733069581177915e-07


  5%|▌         | 8/150 [07:09<2:05:36, 53.07s/it]

Epoch; 7 loss: 1.6607909003596433e-07


  6%|▌         | 9/150 [08:02<2:04:24, 52.94s/it]

Epoch; 8 loss: 1.6818468395740638e-07


  7%|▋         | 10/150 [08:55<2:03:33, 52.96s/it]

Epoch; 9 loss: 1.764653632108093e-07


  7%|▋         | 11/150 [09:48<2:02:35, 52.92s/it]

Epoch; 10 loss: 1.774371725105084e-07


  8%|▊         | 12/150 [10:41<2:01:40, 52.90s/it]

Epoch; 11 loss: 1.6840739647250302e-07


  9%|▊         | 13/150 [11:33<2:00:32, 52.80s/it]

Epoch; 12 loss: 1.6717238793262368e-07


  9%|▉         | 14/150 [12:27<2:00:01, 52.95s/it]

Epoch; 13 loss: 1.7306400934558042e-07


 10%|█         | 15/150 [13:19<1:58:56, 52.87s/it]

Epoch; 14 loss: 1.6903503308185464e-07


 11%|█         | 16/150 [14:12<1:58:14, 52.95s/it]

Epoch; 15 loss: 1.7466345525463112e-07


 11%|█▏        | 17/150 [15:05<1:57:25, 52.98s/it]

Epoch; 16 loss: 1.5992426938282733e-07


 12%|█▏        | 18/150 [15:58<1:56:30, 52.96s/it]

Epoch; 17 loss: 1.675975482839931e-07


 13%|█▎        | 19/150 [16:51<1:55:36, 52.95s/it]

Epoch; 18 loss: 1.725376108652199e-07


 13%|█▎        | 20/150 [17:45<1:55:02, 53.09s/it]

Epoch; 19 loss: 1.752505909280444e-07


 14%|█▍        | 21/150 [18:37<1:53:52, 52.97s/it]

Epoch; 20 loss: 1.7454198086852557e-07


 15%|█▍        | 22/150 [19:31<1:53:17, 53.11s/it]

Epoch; 21 loss: 1.6731409857584367e-07


 15%|█▌        | 23/150 [20:24<1:52:29, 53.15s/it]

Epoch; 22 loss: 1.6731409857584367e-07


 16%|█▌        | 24/150 [21:17<1:51:22, 53.04s/it]

Epoch; 23 loss: 1.6780001033112057e-07


 17%|█▋        | 25/150 [22:10<1:50:29, 53.04s/it]

Epoch; 24 loss: 1.7300327215252764e-07


 17%|█▋        | 26/150 [23:03<1:49:41, 53.07s/it]

Epoch; 25 loss: 1.7344868297186622e-07


 18%|█▊        | 27/150 [23:56<1:48:32, 52.95s/it]

Epoch; 26 loss: 1.6842764694047219e-07


 19%|█▊        | 28/150 [24:49<1:47:44, 52.99s/it]

Epoch; 27 loss: 1.7713348654524452e-07


 19%|█▉        | 29/150 [25:42<1:46:49, 52.97s/it]

Epoch; 28 loss: 1.6986511752747901e-07


 20%|██        | 30/150 [26:35<1:45:56, 52.97s/it]

Epoch; 29 loss: 1.725376108652199e-07


 21%|██        | 31/150 [27:28<1:45:12, 53.04s/it]

Epoch; 30 loss: 1.7138357577550778e-07


 21%|██▏       | 32/150 [28:21<1:44:30, 53.14s/it]

Epoch; 31 loss: 1.7968450549687986e-07


 22%|██▏       | 33/150 [29:15<1:43:55, 53.30s/it]

Epoch; 32 loss: 1.7468370572260028e-07


 23%|██▎       | 34/150 [30:09<1:43:29, 53.53s/it]

Epoch; 33 loss: 1.6782026079908974e-07


 23%|██▎       | 35/150 [31:03<1:42:45, 53.61s/it]

Epoch; 34 loss: 1.7083694103803282e-07


 24%|██▍       | 36/150 [31:57<1:41:59, 53.68s/it]

Epoch; 35 loss: 1.800084419301129e-07


 25%|██▍       | 37/150 [32:50<1:41:10, 53.72s/it]

Epoch; 36 loss: 1.704117664758087e-07


 25%|██▌       | 38/150 [33:45<1:40:42, 53.95s/it]

Epoch; 37 loss: 1.6466186991692666e-07


 26%|██▌       | 39/150 [35:07<1:55:19, 62.34s/it]

Epoch; 38 loss: 1.6941970670814044e-07


 27%|██▋       | 40/150 [36:01<1:49:44, 59.86s/it]

Epoch; 39 loss: 1.8083852637573727e-07


 27%|██▋       | 41/150 [36:55<1:45:38, 58.15s/it]

Epoch; 40 loss: 1.7518985373499163e-07


 28%|██▊       | 42/150 [38:17<1:57:30, 65.28s/it]

Epoch; 41 loss: 1.7146456343652972e-07


 29%|██▊       | 43/150 [39:11<1:50:21, 61.88s/it]

Epoch; 42 loss: 1.772347104633809e-07


 29%|██▉       | 44/150 [40:05<1:45:28, 59.70s/it]

Epoch; 43 loss: 1.7073570290904172e-07


 30%|███       | 45/150 [41:27<1:56:08, 66.37s/it]

Epoch; 44 loss: 1.778218603476489e-07


 31%|███       | 46/150 [42:22<1:48:51, 62.80s/it]

Epoch; 45 loss: 1.7186948753078468e-07


 31%|███▏      | 47/150 [43:16<1:43:30, 60.30s/it]

Epoch; 46 loss: 1.724971241401363e-07


 32%|███▏      | 48/150 [44:11<1:39:35, 58.58s/it]

Epoch; 47 loss: 1.6583614126375323e-07


 33%|███▎      | 49/150 [45:05<1:36:21, 57.24s/it]

Epoch; 48 loss: 1.7211243630299577e-07


 33%|███▎      | 50/150 [46:00<1:34:04, 56.44s/it]

Epoch; 49 loss: 1.7140382624347694e-07


 34%|███▍      | 51/150 [46:54<1:32:03, 55.80s/it]

Epoch; 50 loss: 1.7241613647911436e-07


 35%|███▍      | 52/150 [47:48<1:30:19, 55.31s/it]

Epoch; 51 loss: 1.683264088114811e-07


 35%|███▌      | 53/150 [48:42<1:28:49, 54.95s/it]

Epoch; 52 loss: 1.6907551980693825e-07


 36%|███▌      | 54/150 [49:37<1:27:42, 54.82s/it]

Epoch; 53 loss: 1.6891354448489437e-07


 37%|███▋      | 55/150 [50:31<1:26:33, 54.67s/it]

Epoch; 54 loss: 1.6946019343322405e-07


 37%|███▋      | 56/150 [51:25<1:25:22, 54.50s/it]

Epoch; 55 loss: 1.7707274935219175e-07


 38%|███▊      | 57/150 [52:20<1:24:25, 54.47s/it]

Epoch; 56 loss: 1.6956143156221515e-07


 39%|███▊      | 58/150 [53:14<1:23:19, 54.34s/it]

Epoch; 57 loss: 1.6935896951508767e-07


 39%|███▉      | 59/150 [54:08<1:22:21, 54.30s/it]

Epoch; 58 loss: 1.7148481390449888e-07


 40%|████      | 60/150 [55:02<1:21:32, 54.36s/it]

Epoch; 59 loss: 1.7577698940840492e-07


 41%|████      | 61/150 [55:57<1:20:37, 54.35s/it]

Epoch; 60 loss: 1.6156421622781636e-07


 41%|████▏     | 62/150 [56:50<1:19:29, 54.19s/it]

Epoch; 61 loss: 1.7974524268993264e-07


 42%|████▏     | 63/150 [57:45<1:18:53, 54.41s/it]

Epoch; 62 loss: 1.74238280692407e-07


 43%|████▎     | 64/150 [58:39<1:17:50, 54.30s/it]

Epoch; 63 loss: 1.7387385753409035e-07


 43%|████▎     | 65/150 [59:34<1:17:06, 54.43s/it]

Epoch; 64 loss: 1.7699176169116981e-07


 44%|████▍     | 66/150 [1:00:28<1:16:06, 54.36s/it]

Epoch; 65 loss: 1.6731409857584367e-07


 45%|████▍     | 67/150 [1:01:23<1:15:11, 54.36s/it]

Epoch; 66 loss: 1.683669097474194e-07


 45%|████▌     | 68/150 [1:02:17<1:14:24, 54.45s/it]

Epoch; 67 loss: 1.7369164595493203e-07


 46%|████▌     | 69/150 [1:03:11<1:13:22, 54.35s/it]

Epoch; 68 loss: 1.668686877565051e-07


 47%|████▋     | 70/150 [1:04:06<1:12:35, 54.44s/it]

Epoch; 69 loss: 1.7156580156552081e-07


 47%|████▋     | 71/150 [1:05:01<1:11:48, 54.54s/it]

Epoch; 70 loss: 1.7310449607066403e-07


 48%|████▊     | 72/150 [1:05:55<1:10:44, 54.41s/it]

Epoch; 71 loss: 1.7533157858906634e-07


 49%|████▊     | 73/150 [1:06:49<1:09:46, 54.37s/it]

Epoch; 72 loss: 1.7346893343983538e-07


 49%|████▉     | 74/150 [1:07:44<1:08:52, 54.38s/it]

Epoch; 73 loss: 1.6820493442537554e-07


 50%|█████     | 75/150 [1:08:38<1:08:07, 54.50s/it]

Epoch; 74 loss: 1.6087584242541197e-07


 51%|█████     | 76/150 [1:09:33<1:07:06, 54.42s/it]

Epoch; 75 loss: 1.693387190471185e-07


 51%|█████▏    | 77/150 [1:10:28<1:06:26, 54.61s/it]

Epoch; 76 loss: 1.6601835284291155e-07


 52%|█████▏    | 78/150 [1:11:22<1:05:29, 54.58s/it]

Epoch; 77 loss: 1.6844788319758663e-07


 53%|█████▎    | 79/150 [1:12:17<1:04:41, 54.67s/it]

Epoch; 78 loss: 1.7561502829721576e-07


 53%|█████▎    | 80/150 [1:13:11<1:03:39, 54.56s/it]

Epoch; 79 loss: 1.6549196857340576e-07


 54%|█████▍    | 81/150 [1:14:06<1:02:46, 54.59s/it]

Epoch; 80 loss: 1.7065471524801978e-07


 55%|█████▍    | 82/150 [1:15:01<1:01:54, 54.62s/it]

Epoch; 81 loss: 1.7298302168455848e-07


 55%|█████▌    | 83/150 [1:15:56<1:01:08, 54.75s/it]

Epoch; 82 loss: 1.6320414886195067e-07


 56%|█████▌    | 84/150 [1:16:50<1:00:08, 54.67s/it]

Epoch; 83 loss: 1.7395484519511228e-07


 57%|█████▋    | 85/150 [1:17:45<59:15, 54.69s/it]  

Epoch; 84 loss: 1.7257809759030351e-07


 57%|█████▋    | 86/150 [1:18:39<58:02, 54.41s/it]

Epoch; 85 loss: 1.6917674372507463e-07


 58%|█████▊    | 87/150 [1:19:33<56:57, 54.25s/it]

Epoch; 86 loss: 1.7257809759030351e-07


 59%|█████▊    | 88/150 [1:20:26<55:44, 53.95s/it]

Epoch; 87 loss: 1.7057372758699785e-07


 59%|█████▉    | 89/150 [1:21:21<55:14, 54.33s/it]

Epoch; 88 loss: 1.721934239640177e-07


 60%|██████    | 90/150 [1:22:16<54:29, 54.49s/it]

Epoch; 89 loss: 1.6844788319758663e-07


 61%|██████    | 91/150 [1:23:10<53:29, 54.39s/it]

Epoch; 90 loss: 1.7300327215252764e-07


 61%|██████▏   | 92/150 [1:24:04<52:28, 54.29s/it]

Epoch; 91 loss: 1.74238280692407e-07


 62%|██████▏   | 93/150 [1:24:59<51:39, 54.38s/it]

Epoch; 92 loss: 1.7342844671475177e-07


 63%|██████▎   | 94/150 [1:25:53<50:42, 54.34s/it]

Epoch; 93 loss: 1.692982323220349e-07


 63%|██████▎   | 95/150 [1:26:48<49:56, 54.48s/it]

Epoch; 94 loss: 1.7271982244437822e-07


 64%|██████▍   | 96/150 [1:27:43<49:09, 54.62s/it]

Epoch; 95 loss: 1.7531132812109718e-07


 65%|██████▍   | 97/150 [1:28:38<48:30, 54.92s/it]

Epoch; 96 loss: 1.7523034046007524e-07


 65%|██████▌   | 98/150 [1:29:33<47:29, 54.80s/it]

Epoch; 97 loss: 1.7245662320419797e-07


 66%|██████▌   | 99/150 [1:30:28<46:36, 54.83s/it]

Epoch; 98 loss: 1.7039151600783953e-07


 67%|██████▋   | 100/150 [1:31:23<45:41, 54.82s/it]

Epoch; 99 loss: 1.6986511752747901e-07


 67%|██████▋   | 101/150 [1:32:17<44:46, 54.83s/it]

Epoch; 100 loss: 1.6099731681151752e-07


 68%|██████▊   | 102/150 [1:33:12<43:53, 54.87s/it]

Epoch; 101 loss: 1.663827760012282e-07


 69%|██████▊   | 103/150 [1:34:08<43:05, 55.02s/it]

Epoch; 102 loss: 1.746229685295475e-07


 69%|██████▉   | 104/150 [1:35:03<42:09, 54.99s/it]

Epoch; 103 loss: 1.7454198086852557e-07


 70%|███████   | 105/150 [1:35:58<41:17, 55.06s/it]

Epoch; 104 loss: 1.7148481390449888e-07


 71%|███████   | 106/150 [1:36:53<40:25, 55.13s/it]

Epoch; 105 loss: 1.7624265069571265e-07


 71%|███████▏  | 107/150 [1:37:48<39:30, 55.12s/it]

Epoch; 106 loss: 1.702093044286812e-07


 72%|███████▏  | 108/150 [1:38:43<38:29, 55.00s/it]

Epoch; 107 loss: 1.6160470295289997e-07


 73%|███████▎  | 109/150 [1:39:38<37:33, 54.97s/it]

Epoch; 108 loss: 1.7735619906034117e-07


 73%|███████▎  | 110/150 [1:40:33<36:41, 55.03s/it]

Epoch; 109 loss: 1.6796198565316445e-07


 74%|███████▍  | 111/150 [1:41:28<35:48, 55.10s/it]

Epoch; 110 loss: 1.6998659191358456e-07


 75%|███████▍  | 112/150 [1:42:24<34:54, 55.12s/it]

Epoch; 111 loss: 1.715253006295825e-07


 75%|███████▌  | 113/150 [1:43:19<34:00, 55.14s/it]

Epoch; 112 loss: 1.6780001033112057e-07


 76%|███████▌  | 114/150 [1:44:14<33:01, 55.03s/it]

Epoch; 113 loss: 1.7284129683048377e-07


 77%|███████▋  | 115/150 [1:45:09<32:13, 55.24s/it]

Epoch; 114 loss: 1.7294253495947487e-07


 77%|███████▋  | 116/150 [1:46:31<35:50, 63.24s/it]

Epoch; 115 loss: 1.7357015735797177e-07


 78%|███████▊  | 117/150 [1:47:26<33:21, 60.64s/it]

Epoch; 116 loss: 1.870743346898962e-07


 79%|███████▊  | 118/150 [1:48:20<31:22, 58.84s/it]

Epoch; 117 loss: 1.74096570049187e-07


 79%|███████▉  | 119/150 [1:49:15<29:44, 57.57s/it]

Epoch; 118 loss: 1.752505909280444e-07


 80%|████████  | 120/150 [1:50:09<28:16, 56.53s/it]

Epoch; 119 loss: 1.7144431296856055e-07


 81%|████████  | 121/150 [1:51:04<27:01, 55.93s/it]

Epoch; 120 loss: 1.701688177035976e-07


 81%|████████▏ | 122/150 [1:51:58<25:57, 55.61s/it]

Epoch; 121 loss: 1.622728262873352e-07


 82%|████████▏ | 123/150 [1:52:52<24:47, 55.10s/it]

Epoch; 122 loss: 1.762224144385982e-07


 83%|████████▎ | 124/150 [1:53:47<23:45, 54.83s/it]

Epoch; 123 loss: 1.7577698940840492e-07


 83%|████████▎ | 125/150 [1:54:42<22:56, 55.06s/it]

Epoch; 124 loss: 1.7755864689661394e-07


 84%|████████▍ | 126/150 [1:55:38<22:03, 55.15s/it]

Epoch; 125 loss: 1.7435976928936725e-07


 85%|████████▍ | 127/150 [1:56:31<20:58, 54.70s/it]

Epoch; 126 loss: 1.6403423330757505e-07


 85%|████████▌ | 128/150 [1:57:26<20:04, 54.74s/it]

Epoch; 127 loss: 1.6403423330757505e-07


 86%|████████▌ | 129/150 [1:58:21<19:08, 54.68s/it]

Epoch; 128 loss: 1.759794514555324e-07


 87%|████████▋ | 130/150 [1:59:14<18:08, 54.43s/it]

Epoch; 129 loss: 1.7610092584163795e-07


 87%|████████▋ | 131/150 [2:00:09<17:14, 54.43s/it]

Epoch; 130 loss: 1.7073570290904172e-07


 88%|████████▊ | 132/150 [2:01:03<16:20, 54.48s/it]

Epoch; 131 loss: 1.6634228927614458e-07


 89%|████████▊ | 133/150 [2:01:57<15:23, 54.30s/it]

Epoch; 132 loss: 1.7713348654524452e-07


 89%|████████▉ | 134/150 [2:02:52<14:28, 54.31s/it]

Epoch; 133 loss: 1.7393459472714312e-07


 90%|█████████ | 135/150 [2:03:46<13:35, 54.38s/it]

Epoch; 134 loss: 1.7589846379451046e-07


 91%|█████████ | 136/150 [2:04:40<12:39, 54.25s/it]

Epoch; 135 loss: 1.695816678193296e-07


 91%|█████████▏| 137/150 [2:05:34<11:43, 54.15s/it]

Epoch; 136 loss: 1.7812554631291277e-07


 92%|█████████▏| 138/150 [2:06:29<10:51, 54.27s/it]

Epoch; 137 loss: 1.7557452736127743e-07


 93%|█████████▎| 139/150 [2:07:23<09:56, 54.26s/it]

Epoch; 138 loss: 1.7359040782594093e-07


 93%|█████████▎| 140/150 [2:08:45<10:25, 62.56s/it]

Epoch; 139 loss: 1.6873133290573605e-07


 94%|█████████▍| 141/150 [2:09:39<09:01, 60.16s/it]

Epoch; 140 loss: 1.71322838582455e-07


 95%|█████████▍| 142/150 [2:10:34<07:49, 58.63s/it]

Epoch; 141 loss: 1.739953319201959e-07


 95%|█████████▌| 143/150 [2:11:29<06:42, 57.46s/it]

Epoch; 142 loss: 1.7255786133318907e-07


 96%|█████████▌| 144/150 [2:12:24<05:40, 56.68s/it]

Epoch; 143 loss: 1.6996635565647011e-07


 97%|█████████▋| 145/150 [2:13:19<04:41, 56.23s/it]

Epoch; 144 loss: 1.7290203402353654e-07


 97%|█████████▋| 146/150 [2:14:14<03:43, 55.79s/it]

Epoch; 145 loss: 1.7049275413683063e-07


 98%|█████████▊| 147/150 [2:15:08<02:46, 55.40s/it]

Epoch; 146 loss: 1.6765828547704587e-07


 99%|█████████▊| 148/150 [2:16:04<01:50, 55.40s/it]

Epoch; 147 loss: 1.7251736039725074e-07


 99%|█████████▉| 149/150 [2:16:58<00:55, 55.07s/it]

Epoch; 148 loss: 1.6931846857914934e-07


100%|██████████| 150/150 [2:17:53<00:00, 55.16s/it]

Epoch; 149 loss: 1.7140382624347694e-07


([<tf.Tensor: shape=(), dtype=float32, numpy=1.7672856e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.6903503e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7255786e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7188974e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7557453e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.6927798e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7330696e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.6607909e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.6818468e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7646536e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7743717e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.684074e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.6717239e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7306401e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.6903503e-07>,
  <tf.Tensor: shape=(), dtype=float32, numpy=1.7466346e-07>,
  <tf.Tensor: shape=(), d

In [18]:
base_encoder_model.save("simclr_model_1")
keras.backend.clear_session() 